# Generated by Django 5.2.6 on 2025-09-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('policy_tags', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ProvenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64)),
                ('step_no', models.IntegerField()),
                ('actor', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('input_hash', models.CharField(blank=True, max_length=128)),
                ('output_hash', models.CharField(blank=True, max_length=128)),
                ('policy_decision', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'provenance_log',
                'unique_together': {('run_id', 'step_no')},
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('embedding', models.BinaryField()),
                ('dim', models.IntegerField()),
                ('model', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='store.document')),
            ],
            options={
                'db_table': 'vectors',
            },
        ),
    ]
